seleniumgrid=true
grid_url = http://localhost:4444/


url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
local_url = http://localhost/orangehrm/orangehrm-5.8/web/index.php/auth/login
url_grid = http://host.docker.internal/orangehrm/orangehrm-5.8/web/index.php/auth/login

browser = firefox

username =orangehrm1
password = aDmin$1234

implicitwait= 5

explicitwait =5